Use new format and misc updates

diff --git a/tag-wp/bin/demyx-install b/tag-wp/bin/demyx-install
--- a/tag-wp/bin/demyx-install
+++ b/tag-wp/bin/demyx-install
@@ -2,34 +2,58 @@
 # Demyx
 # https://demyx.sh
 set -euo pipefail
+#
+#   Main.
+#
+demyx_install() {
+    # Support for old variables
+    [[ -n "${WORDPRESS_DB_HOST:-}" ]] && DEMYX_DB_HOST="$WORDPRESS_DB_HOST"
+    [[ -n "${WORDPRESS_DB_NAME:-}" ]] && DEMYX_DB_NAME="$WORDPRESS_DB_NAME"
+    [[ -n "${WORDPRESS_DB_PASSWORD:-}" ]] && DEMYX_DB_PASSWORD="$WORDPRESS_DB_PASSWORD"
+    [[ -n "${WORDPRESS_DB_USER:-}" ]] && DEMYX_DB_USERNAME="$WORDPRESS_DB_USER"
+    [[ -n "${WORDPRESS_DOMAIN:-}" ]] && DEMYX_DOMAIN="$WORDPRESS_DOMAIN"
 
-# Support for old variables
-[[ -n "${WORDPRESS_DB_HOST:-}" ]] && DEMYX_DB_HOST="$WORDPRESS_DB_HOST"
-[[ -n "${WORDPRESS_DB_NAME:-}" ]] && DEMYX_DB_NAME="$WORDPRESS_DB_NAME"
-[[ -n "${WORDPRESS_DB_PASSWORD:-}" ]] && DEMYX_DB_PASSWORD="$WORDPRESS_DB_PASSWORD"
-[[ -n "${WORDPRESS_DB_USER:-}" ]] && DEMYX_DB_USER="$WORDPRESS_DB_USER"
+    demyx_install_config
+}
+#
+#   Config.
+#
+demyx_install_config() {
+    local DEMYX_INSTALL_CHECK=
 
-if [[ ! -d "$DEMYX"/wp-admin ]]; then
-    echo "[demyx] WordPress is missing, copying files now ..."
-    tar -xzf "$DEMYX_CONFIG"/wordpress.tgz -C "$DEMYX"
-fi
+    if [[ ! -d "$DEMYX"/wp-admin ]]; then
+        echo "[demyx] WordPress is missing, copying files now ..."
+        tar -xzf "$DEMYX_CONFIG"/wordpress.tgz -C "$DEMYX"
+    fi
 
-if [[ -n "$(grep database_name_here "$DEMYX_WP_CONFIG" || true)" ]]; then
-    echo "[demyx] Configuring wp-config.php ..."
-    sed -i "s|database_name_here|${DEMYX_DB_NAME}|g" "$DEMYX_WP_CONFIG"
-    sed -i "s|username_here|${DEMYX_DB_USER}|g" "$DEMYX_WP_CONFIG"
-    sed -i "s|password_here|${DEMYX_DB_PASSWORD}|g" "$DEMYX_WP_CONFIG"
-    sed -i "s|localhost|${DEMYX_DB_HOST}|g" "$DEMYX_WP_CONFIG"
+    DEMYX_INSTALL_CHECK="$(grep "username_here" "$DEMYX_WP_CONFIG" || true)"
+    if [[ -n "$DEMYX_INSTALL_CHECK" ]]; then
+        # Generate wp-config.php
+        wp config create \
+            --dbhost="$DEMYX_DB_HOST" \
+            --dbname="$DEMYX_DB_NAME" \
+            --dbpass="$DEMYX_DB_PASSWORD" \
+            --dbuser="$DEMYX_DB_USERNAME" \
+            --force
 
-    wp core install \
-        --url="${DEMYX_DOMAIN:-}" \
-        --title="${DEMYX_DOMAIN:-}" \
-        --admin_user="${DEMYX_ADMIN_USERNAME:-}" \
-        --admin_password="${DEMYX_ADMIN_PASSWORD:-}" \
-        --admin_email="${DEMYX_ADMIN_EMAIL:-}" \
-        --skip-email
-    wp rewrite structure '/%category%/%postname%/'
-    wp config shuffle-salts
+        # Configure wp-config.php
+        # shellcheck disable=SC2153
+        wp core install \
+            --admin_email="$DEMYX_WP_EMAIL" \
+            --admin_password="$DEMYX_WP_PASSWORD" \
+            --admin_user="$DEMYX_WP_USERNAME" \
+            --skip-email \
+            --title="$DEMYX_DOMAIN" \
+            --url="${DEMYX_PROTO}://${DEMYX_DOMAIN}"
 
-    sed -i "s|\$table_prefix = 'wp_';|\$table_prefix = 'wp_';\n\n\/\/ If we're behind a proxy server and using HTTPS, we need to alert Wordpress of that fact\n\/\/ see also http:\/\/codex.wordpress.org\/Administration_Over_SSL#Using_a_Reverse_Proxy\nif (isset($\_SERVER['HTTP_X_FORWARDED_PROTO']) \&\& $\_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {\n\t$\_SERVER['HTTPS'] = 'on';\n}\n|g" "$DEMYX_WP_CONFIG"
-fi
+        # Update permalinks
+        wp rewrite structure '/%category%/%postname%/'
+
+        # Update timezone
+        wp option update timezone_string "$TZ"
+    fi
+}
+#
+#   Init.
+#
+demyx_install
