tag-openlitespeed - Added     - `bin/demyx-admin`     - `bin/demyx-config`     - `bin/demyx-entrypoint`     - `bin/demyx-htpasswd`     - `bin/demyx-install`     - `bin/demyx-lsws`     - `config/.demyxrc`     - `config/.p10k.zsh`     - `config/bs.php`     - `config/launch.json`     - `config/settings.json`     - `config/shevaua.phpcs-1.0.8.vsix` - Changed     - Update directory structure.     - `bin/demyx-admin`         - Replace OPENLITESPEED_ with DEMYX_ prefix for variables.         - Support for old variables.     - `bin/demyx-config`         - Replace OPENLITESPEED_ with DEMYX_ prefix for variables.         - Support for old variables.     - `bin/demyx-encrypt`         - Replace OPENLITESPEED_ with DEMYX_ prefix for variables.         - Support for old variables.     - `bin/demyx-entrypoint`         - Update code-server variables.         - Support for old variables.         - Migrate oh-my-zsh plugins to custom directory.         - Make oh-my-zsh, custom themes, and plugins auto update.         - Source `.demyxrc` in .zshrc.         - Migrate code-server data and extensions directory.         - code-server now uses config.yaml for its configs.     - `bin/demyx-htpasswd`         - Replace OPENLITESPEED_ with DEMYX_ prefix for variables.     - `bin/demyx-install`         - Replace OPENLITESPEED_ with DEMYX_ prefix for variables.         - Support for old variables.     - `bin/demyx-lsws`         - Replace OPENLITESPEED_ with DEMYX_ prefix for variables.     - `config/.demyxrc`         - oh-my-zsh config variables.         - Other misc variables.     - `config/launch.json`         - Remove unused items.     - `config/settings.json`         - Set default font family.         - Removed some items.     - `docker-compose.yml`         - Downgrade version to 2.4.         - Alphabetize keys.         - Update variables with DEMYX_ prefix.         - Various misc updates.     - `Dockerfile`         - Remove FROM demyx/openlitespeed.         - Add shellcheck.         - All main variables are now prefixed with DEMYX_.         - Import ENVs from demyx/wordpress image.         - Update ENVs with additional variables.         - Rearrange RUN commands.         - Update packages.         - Update bash PS1.         - Update Xdebug to 3.x.         - Set default theme to powerlevel10k.         - Dynamically update code-server version by curling its GitHub repo.         - Support custom fonts needed by powerlevel10k theme. - Removed

diff --git a/tag-openlitespeed/Dockerfile b/tag-openlitespeed/Dockerfile
--- a/tag-openlitespeed/Dockerfile
+++ b/tag-openlitespeed/Dockerfile
@@ -1,129 +1,266 @@
-FROM demyx/openlitespeed
+FROM koalaman/shellcheck as demyx_shellcheck
+FROM debian:buster-slim
 
-LABEL sh.demyx.image        demyx/code-server:openlitespeed
-LABEL sh.demyx.maintainer   Demyx <info@demyx.sh>
-LABEL sh.demyx.url          https://demyx.sh
-LABEL sh.demyx.github       https://github.com/demyxco
-LABEL sh.demyx.registry     https://hub.docker.com/u/demyx
+LABEL sh.demyx.image                            demyx/code-server:openlitespeed
+LABEL sh.demyx.maintainer                       Demyx <info@demyx.sh>
+LABEL sh.demyx.url                              https://demyx.sh
+LABEL sh.demyx.github                           https://github.com/demyxco
+LABEL sh.demyx.registry                         https://hub.docker.com/u/demyx
 
-ENV CODE_PHP     php7.4
+# Set default variables
+ENV DEMYX                                       /demyx
+ENV DEMYX_ADMIN                                 /demyx/ols
+ENV DEMYX_ADMIN_EMAIL                           info@localhost
+ENV DEMYX_ADMIN_IP                              ALL
+ENV DEMYX_ADMIN_PASSWORD                        demyx
+ENV DEMYX_ADMIN_PREFIX                          true
+ENV DEMYX_ADMIN_USERNAME                        demyx
+ENV DEMYX_BASIC_AUTH_PASSWORD                   demyx
+ENV DEMYX_BASIC_AUTH_USERNAME                   demyx
+ENV DEMYX_BASIC_AUTH_WP                         false
+ENV DEMYX_CACHE                                 false
+ENV DEMYX_CLIENT_THROTTLE_BANDWIDTH_IN          0
+ENV DEMYX_CLIENT_THROTTLE_BANDWIDTH_OUT         0
+ENV DEMYX_CLIENT_THROTTLE_BAN_PERIOD            60
+ENV DEMYX_CLIENT_THROTTLE_BLOCK_BAD_REQUEST     1
+ENV DEMYX_CLIENT_THROTTLE_DYNAMIC               1000
+ENV DEMYX_CLIENT_THROTTLE_GRACE_PERIOD          30
+ENV DEMYX_CLIENT_THROTTLE_HARD_LIMIT            2000
+ENV DEMYX_CLIENT_THROTTLE_SOFT_LIMIT            1500
+ENV DEMYX_CLIENT_THROTTLE_STATIC                1000
+ENV DEMYX_CODE_AUTH                             password
+ENV DEMYX_CODE_BIND_ADDR                        0.0.0.0:8080
+ENV DEMYX_CODE_CONFIG                           /home/demyx/.config/code-server
+ENV DEMYX_CODE_PASSWORD                         demyx
+ENV DEMYX_CONFIG                                /etc/demyx
+ENV DEMYX_CRAWLER_LOAD_LIMIT                    5.2
+ENV DEMYX_CRAWLER_USLEEP                        1000
+ENV DEMYX_DB_HOST                               localhost
+ENV DEMYX_DB_NAME                               demyx
+ENV DEMYX_DB_PASSWORD                           demyx
+ENV DEMYX_DB_USER                               demyx
+ENV DEMYX_DOMAIN                                localhost
+ENV DEMYX_LOG                                   /var/log/demyx
+ENV DEMYX_LSPHP_VERSION                         lsphp74
+ENV DEMYX_PHP_LSAPI_CHILDREN                    2000
+ENV DEMYX_PHP_MAX_EXECUTION_TIME                300
+ENV DEMYX_PHP_MEMORY                            256M
+ENV DEMYX_PHP_OPCACHE                           true
+ENV DEMYX_PHP_UPLOAD_LIMIT                      128M
+ENV DEMYX_RECAPTCHA_CONNECTION_LIMIT            500
+ENV DEMYX_RECAPTCHA_ENABLE                      1
+ENV DEMYX_RECAPTCHA_TYPE                        2
+ENV DEMYX_TUNING_CONNECTION_TIMEOUT             300
+ENV DEMYX_TUNING_KEEP_ALIVE_TIMEOUT             300
+ENV DEMYX_TUNING_MAX_CONNECTIONS                20000
+ENV DEMYX_TUNING_MAX_KEEP_ALIVE                 1000
+ENV DEMYX_TUNING_SMART_KEEP_ALIVE               1000
+ENV DEMYX_WP_CONFIG                             "${DEMYX}/wp-config.php"
+ENV DEMYX_XMLRPC                                false
+ENV PATH                                        "${PATH}:/usr/local/lsws/${DEMYX_LSPHP_VERSION}/bin"
+ENV TERM                                        xterm-256color
+ENV TZ                                          America/Los_Angeles
+# Support for old variables
+ENV CODE_ROOT                                   "$DEMYX"
+ENV CODE_CONFIG                                 "$DEMYX_CONFIG"
+ENV CODE_LOG                                    "$DEMYX_LOG"
 
-# Run as root for now
-USER root
-
-# Packages 
+# Packages
 RUN set -ex; \
     apt-get update && apt-get install -y --no-install-recommends \
-    curl \
-    gcc \
-    git \
-    gnupg \
-    htop \
-    jq \
-    less \
-    nano \
-    net-tools \
-    openssh-client \
-    util-linux \
-    wget \
-    zsh; \
-    \
-    apt-get install -y --no-install-recommends \
-    apt-transport-https \
-    ca-certificates \
-    lsb-release; \
-    \
-    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg; \
-    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list; \
-    apt-get update && apt-get install -y --no-install-recommends \
-    "$CODE_PHP" \
-    "$CODE_PHP"-mysql; \
-    \
-    rm -rf /var/lib/apt/lists/*
+        apt-transport-https \
+        bash \
+        bsdmainutils \
+        ca-certificates \
+        curl \
+        dnsutils \
+        git \
+        gnupg \
+        htop \
+        iputils-ping \
+        jq \
+        less \
+        lsb-release \
+        nano \
+        net-tools \
+        openssh-client \
+        procps \
+        ruby \
+        sudo \
+        tzdata \
+        unzip \
+        util-linux \
+        wget \
+        zsh
 
-# Oh-My-Zsh
+# Configure Demyx
 RUN set -ex; \
-    sed -i "s|/home/demyx:/sbin/nologin|/home/demyx:/bin/zsh|g" /etc/passwd; \
-    echo "demyx ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/demyx; \
+    # Create demyx user
+    adduser --gecos '' --disabled-password demyx; \
     \
-    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"; \
-    git clone https://github.com/zsh-users/zsh-autosuggestions.git /root/.oh-my-zsh/plugins/zsh-autosuggestions; \
-    sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="ys"/g' /root/.zshrc; \
-    sed -i "s/(git)/(git zsh-autosuggestions)/g" /root/.zshrc; \
+    # Update .bashrc
+    echo 'PS1="$(whoami)@\h:\w \$ "' > /home/demyx/.bashrc; \
+    echo 'PS1="$(whoami)@\h:\w \$ "' > /root/.bashrc; \
     \
+    # Create demyx directories
+    install -d -m 0755 -o demyx -g demyx "$DEMYX"; \
+    install -d -m 0755 -o demyx -g demyx "$DEMYX_CONFIG"; \
+    install -d -m 0755 -o demyx -g demyx "$DEMYX_LOG"; \
+    \
+    # Oh-My-Zsh
     su -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" -s /bin/sh demyx; \
-    git clone https://github.com/zsh-users/zsh-autosuggestions.git /home/demyx/.oh-my-zsh/plugins/zsh-autosuggestions; \
-    sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="ys"/g' /home/demyx/.zshrc; \
-    sed -i "s/(git)/(git zsh-autosuggestions)/g" /home/demyx/.zshrc; \
+    su -c "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /home/demyx/.oh-my-zsh/custom/themes/powerlevel10k" -s /bin/sh demyx; \
+    su -c "git clone https://github.com/zsh-users/zsh-autosuggestions.git /home/demyx/.oh-my-zsh/custom/plugins/zsh-autosuggestions" -s /bin/sh demyx; \
+    su -c "git clone https://github.com/TamCore/autoupdate-oh-my-zsh-plugins.git /home/demyx/.oh-my-zsh/custom/plugins/autoupdate" -s /bin/sh demyx; \
+    sed -i 's|source $ZSH/oh-my-zsh.sh|source "$DEMYX_CONFIG"/.demyxrc\nsource $ZSH/oh-my-zsh.sh|g' /home/demyx/.zshrc; \
     \
-    # Symlink demyx command history with root
-    ln -s /home/demyx/.zsh_history /root; \
+    # Change user shell
+    sed -i "s|/home/demyx:/sbin/nologin|/home/demyx:/bin/zsh|g" /etc/passwd
+
+# OpenLiteSpeed
+RUN set -ex; \
+    DEMYX_OLS_VERSION="$(wget -qO- https://api.github.com/repos/litespeedtech/openlitespeed/tags 2>&1 | jq -r '.[].name' | head -n 1 | sed 's|v||g')"; \
+    wget https://openlitespeed.org/packages/openlitespeed-"$DEMYX_OLS_VERSION".tgz -qO /tmp/openlitespeed-"$DEMYX_OLS_VERSION".tgz; \
+    tar -xzf /tmp/openlitespeed-"$DEMYX_OLS_VERSION".tgz -C /tmp; \
+    cd /tmp/openlitespeed && ./install.sh; \
     \
-    # Change root shell
-    sed -i "s|/root:/bin/bash|/root:/bin/zsh|g" /etc/passwd; \
+    wget -O - https://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh | bash; \
     \
-    # gpg purposes
-    echo 'export GPG_TTY=$(tty)' >> /root/.zshrc; \
-    echo 'export GPG_TTY=$(tty)' >> /home/demyx/.zshrc; \
+    apt-get update && apt-get install -y \
+        "$DEMYX_LSPHP_VERSION" \
+        "$DEMYX_LSPHP_VERSION"-curl \
+        "$DEMYX_LSPHP_VERSION"-imagick \
+        "$DEMYX_LSPHP_VERSION"-json \
+        "$DEMYX_LSPHP_VERSION"-mysql; \
     \
-    # Copy .zshrc to config directory
-    cp /home/demyx/.zshrc "$OPENLITESPEED_CONFIG"
+    ln -sf /usr/local/lsws/"$DEMYX_LSPHP_VERSION"/bin/lsphp /usr/local/lsws/fcgi-bin/lsphp5; \
+    \
+    # Create directory for lsadm user
+    install -d -m 0755 -o lsadm -g lsadm "$DEMYX_CONFIG"/ols; \
+    \
+    # Symlink configs to lsws
+    ln -sf "$DEMYX_CONFIG"/ols/httpd_config.conf /usr/local/lsws/conf/httpd_config.conf; \
+    ln -sf "$DEMYX_CONFIG"/ols/admin_config.conf /usr/local/lsws/admin/conf/admin_config.conf; \
+    ln -s "$DEMYX_CONFIG"/ols /usr/local/lsws/conf/vhosts
+
+# Composer
+RUN set -ex; \
+    curl -sL https://getcomposer.org/installer -o /tmp/composer-setup.php; \
+    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
+
+# PHP CodeSniffer & WPCS
+RUN set -ex; \
+    su -c "mkdir \"$DEMYX_CONFIG\"/phpcs && cd \"$DEMYX_CONFIG\"/phpcs; \
+    composer require \"squizlabs/php_codesniffer=*\"; \
+    cd .. && git clone -b master https://github.com/WordPress/WordPress-Coding-Standards.git wpcs; \
+    \"$DEMYX_CONFIG\"/phpcs/vendor/bin/phpcs --config-set installed_paths ${DEMYX_CONFIG}/wpcs" -s /bin/sh demyx; \
+    ln -s "$DEMYX_CONFIG"/phpcs/vendor/bin/phpcs /usr/local/bin/phpcs
+
+# Xdebug
+RUN set -ex; \
+    apt-get install -y "$DEMYX_LSPHP_VERSION"-pear; \
+    \
+    ln -s /bin/sed /usr/bin/sed; \
+    \
+    pecl install xdebug; \
+    \
+    DEMYX_FIND_XDEBUG="$(find /usr/local/lsws -name "xdebug.so")"; \
+    DEMYX_FIND_INI="$(find /usr/local/lsws -name "php.ini" 2>&1 | grep lsphp)"; \
+    \
+    echo "[XDebug]\nzend_extension = ${DEMYX_FIND_XDEBUG}\nxdebug.client_port = 9001\nxdebug.mode = debug\nxdebug.start_with_request = trigger\nxdebug.trigger_value = 1" >> "$DEMYX_FIND_INI"; \
+    \
+    apt-get purge -y "$DEMYX_LSPHP_VERSION"-pear; \
+    apt-get autoremove -y
+
+# WordPress
+RUN set -ex; \
+    su -c "wget https://wordpress.org/latest.tar.gz -qO /tmp/latest.tar.gz; \
+        \
+        tar -xzf /tmp/latest.tar.gz -C /tmp; \
+        \
+        mv /tmp/wordpress/wp-config-sample.php /tmp/wordpress/wp-config.php; \
+        \
+        cp -r /tmp/wordpress/* ${DEMYX}; \
+        \
+        tar -czf ${DEMYX_CONFIG}/wordpress.tgz -C /tmp/wordpress ." -s /bin/sh demyx
 
 # wp-cli
 RUN set -ex; \
-    curl -s https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/local/bin/wp; \
+    curl -sL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/local/bin/wp; \
     chmod +x /usr/local/bin/wp
 
-# Copy source & binary
-COPY --chown=demyx:demyx src "$OPENLITESPEED_CONFIG"
+# Imports
+COPY --from=demyx_shellcheck /bin/shellcheck /usr/local/bin/shellcheck
+COPY --chown=root:root bin /usr/local/bin
+COPY --chown=demyx:demyx config "$DEMYX_CONFIG"
 
 # Configure code-server
 RUN set -ex; \
     # Get code-server
-    CODE_VERSION=$(curl -sL https://api.github.com/repos/cdr/code-server/releases/latest | grep '"name"' | head -1 | awk -F '[:]' '{print $2}' | sed -e 's/"//g' | sed -e 's/,//g' | sed -e 's/ //g' | sed -e 's/\r//g'); \
+    CODE_VERSION="$(curl -sL https://api.github.com/repos/cdr/code-server/releases/latest | jq -r .tag_name)"; \
+    if [ -z "$CODE_VERSION" ]; then CODE_VERSION=v3.8.0; fi; \
     CODE_VERSION_NUMBER="$(echo "$CODE_VERSION" | sed 's|v||g')"; \
-    curl -sL https://github.com/cdr/code-server/releases/download/"$CODE_VERSION"/code-server-"$CODE_VERSION_NUMBER"-linux-amd64.tar.gz -o /tmp/code-server-"$CODE_VERSION"-linux-amd64.tar.gz; \         
+    curl -sL https://github.com/cdr/code-server/releases/download/"$CODE_VERSION"/code-server-"$CODE_VERSION_NUMBER"-linux-amd64.tar.gz -o /tmp/code-server-"$CODE_VERSION"-linux-amd64.tar.gz; \
     tar -xzf /tmp/code-server-"$CODE_VERSION"-linux-amd64.tar.gz -C /tmp; \
     mv /tmp/code-server-"$CODE_VERSION_NUMBER"-linux-amd64 /usr/local/lib/code-server; \
     \
     # Create code-server directories
-    install -d -m 0755 -o demyx -g demyx /home/demyx/.code/extensions; \
-    install -d -m 0755 -o demyx -g demyx /home/demyx/.code/data/User; \
+    install -d -m 0755 -o demyx -g demyx "$DEMYX_CODE_CONFIG"/data/User; \
+    install -d -m 0755 -o demyx -g demyx "$DEMYX_CODE_CONFIG"/extensions; \
     \
-    # Get remote files
-    curl -sL https://github.com/demyxco/code-server/raw/master/shared/bs.php -o "$OPENLITESPEED_CONFIG"/bs.php; \
-    curl -sL https://github.com/demyxco/code-server/raw/master/shared/settings-wp.json -o /home/demyx/.code/data/User/settings.json; \
+    # Copy settings.json
+    cp "$DEMYX_CONFIG"/settings.json "$DEMYX_CODE_CONFIG"/data/User/settings.json; \
     \
     # Symlink code-server
     ln -s /usr/local/lib/code-server/bin/code-server /usr/local/bin/code-server; \
     \
     # Install default extensions
-    code-server --extensions-dir=/home/demyx/.code/extensions \
-    --install-extension=equinusocio.vsc-material-theme \
-    --install-extension=pkief.material-icon-theme; \
+    code-server --extensions-dir="$DEMYX_CODE_CONFIG"/extensions \
+        --install-extension=equinusocio.vsc-material-theme \
+        --install-extension=pkief.material-icon-theme \
+        --install-extension=remisa.shellman \
+        --install-extension=ryu1kn.partial-diff \
+        --install-extension=timonwong.shellcheck; \
     \
-    # Set ownership
-    chown -R demyx:demyx /home/demyx/.code; \
-    chown -R demyx:demyx "$OPENLITESPEED_CONFIG"; \
+    # Tag specifc extensions
+    code-server --extensions-dir="$DEMYX_CODE_CONFIG"/extensions \
+        --install-extension="$DEMYX_CONFIG"/shevaua.phpcs-1.0.8.vsix \
+        --install-extension=felixfbecker.php-debug; \
     \
-    # Make a copy to demyx config directory
-    cp -rp /home/demyx/.code "$OPENLITESPEED_CONFIG"/code
+    # Custom fonts
+    sed -i "s|</head>|\
+    <style> \n\
+        @font-face { \n\
+        font-family: 'MesloLGS NF'; \n\
+        font-style: normal; \n\
+        src: url('https://demyx.sh/fonts/meslolgs-nf-regular.woff') format('woff'), \n\
+        url('https://demyx.sh/fonts/meslolgs-nf-bold.woff') format('woff'), \n\
+        url('https://demyx.sh/fonts/meslolgs-nf-italic.woff') format('woff'), \n\
+        url('https://demyx.sh/fonts/meslolgs-nf-bold-italic.woff') format('woff'); \n\
+    } \n\
+    \n\</style></head>|g" /usr/local/lib/code-server/src/browser/pages/vscode.html; \
+    \
+    # Finalize code-server
+    chown -R demyx:demyx "$DEMYX_CODE_CONFIG"; \
+    chown -R demyx:demyx "$DEMYX_CONFIG"; \
+    cp -rp "$DEMYX_CODE_CONFIG" "$DEMYX_CONFIG"
 
 # Finalize
 RUN set -ex; \
-    # demyx-install
-    chmod +x "$OPENLITESPEED_CONFIG"/install.sh; \
-    mv "$OPENLITESPEED_CONFIG"/install.sh /usr/local/bin/demyx-install; \
-    \
-    # demyx-entrypoint
-    chmod +x "$OPENLITESPEED_CONFIG"/entrypoint.sh; \
-    mv "$OPENLITESPEED_CONFIG"/entrypoint.sh /usr/local/bin/demyx-entrypoint; \
+    # sudoers
+    echo "demyx ALL=(ALL) NOPASSWD:SETENV: /usr/local/lsws/bin/lswsctrl, /usr/local/bin/demyx-admin, /usr/local/bin/demyx-config, /usr/local/bin/demyx-htpasswd, /usr/local/bin/demyx-lsws" > /etc/sudoers.d/demyx; \
     \
     # Set ownership
-    chown -R root:root /usr/local/bin
+    chown -R root:root /usr/local/bin; \
+    \
+    # Cleanup
+    rm -rf /var/lib/apt/lists/*; \
+    rm -rf /tmp/*
 
-# Expose code-server port
-EXPOSE 80 8080 8081
+EXPOSE 80 8080 8081 9000 9001
 
-# Set back to demyx
+WORKDIR "$DEMYX"
+
 USER demyx
+
+ENTRYPOINT ["demyx-entrypoint"]
